baseURL = 'http://resilientfintech.com/'
languageCode = 'en-us'
title = 'Resilient fintech'
theme = 'etch'

[params]
  description = "Living and thriving at intersection of product, finance and tech."


