baseURL = 'http://resilientfintech.com/'
languageCode = 'en-us'
title = 'Resilient fintech'
theme = 'hugo-etch'

enableRobotsTXT = true
canonifyURLs = true

[params]
  description = "Living and thriving at intersection of product, finance and tech."


